name: telegram

on:
  push:
    branches: [ master ]  
  release:    
    types:
      - published    
jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - uses: Kezii/telegram-github-action@master
      env:
        telegram_to: ${{ secrets.telegram_to }}  
        telegram_token: ${{ secrets.telegram_token }}
        message_thread_id: ${{ secrets.telegram_message_thread_id }}
        event: ${{ toJson(github.event) }}
