name: telegram

on:
  push:
    branches: [ master ]  
  release:    
    types:
      - published    
jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:        
    - uses: Kezii/telegram-github-action@v9
      env:
        telegram_to: ${{ secrets.telegram_to }}  
        telegram_token: ${{ secrets.telegram_token }}
        message_thread_id: ${{ secrets.telegram_message_thread_id }}
        event: ${{ toJson(github.event) }}
